Repository virtualdj/pun_sensor, pull requests merged in 2025-01, with the labels that each got.

#74 Fix calcolo PUN a fine mese; closes #73
  custom_components/pun_sensor/coordinator.py
Labels: patch

#76 Aggiunta validazione con Ruff nelle GitHub Actions
  .github/workflows/validate.yaml
Labels: maintenance

#81 Mostra la versione di HA nel Devcontainer
  .vscode/tasks.json
Labels: patch, maintenance

#79 config_entry assignation is deprecated
  custom_components/pun_sensor/config_flow.py
Labels: bug, minor

#80 Fix lint
  custom_components/pun_sensor/coordinator.py
  pyproject.toml
Labels: patch, maintenance
